name: Build Kivy APK

on:
  workflow_dispatch: # Allows you to manually trigger the run from the Actions tab
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies required for Buildozer and Android SDK
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          openjdk-17-jdk \
          zip \
          unzip \
          git \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses-dev \  # Changed from libncurses5-dev
          libgdbm-dev \
          libsqlite3-dev \
          libssl-dev \
          libreadline-dev \
          libffi-dev \
          liblzma-dev

      # Step 3: Install Python dependencies (Buildozer)
      - name: Install Buildozer
        run: pip install buildozer cython==0.29.33

      # Step 4: Initialize Buildozer if no spec file exists (comment out after first run)
      # - name: Buildozer init
      #   run: buildozer init

      # Step 5: Build the Android APK (Debug)
      - name: Build APK with Buildozer
        run: |
          buildozer android debug
        env:
          # This is often needed in CI environments
          PACKAGES_PATH: ${{ github.workspace }}/.buildozer/android/packages

      # Step 6: Upload the built APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
