name: Build Kivy APK

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          openjdk-17-jdk \
          zip \
          unzip \
          git \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses-dev \
          libgdbm-dev \
          libsqlite3-dev \
          libssl-dev \
          libreadline-dev \
          libffi-dev \
          liblzma-dev

      - name: Install Buildozer
        run: pip install buildozer cython==0.29.33

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
        env:
          PACKAGES_PATH: ${{ github.workspace }}/.buildozer/android/packages

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
